import type { GeneratedParlay } from '@shared/types'
import { Linking, Pressable, StyleSheet, Text, View } from 'react-native'

import { LegalDisclaimer } from '@/components/legal/LegalDisclaimer'
import { colors, HIT_SLOP, spacing, typography } from '@/lib/theme/designTokens'

const NFLVERSE_URL = 'https://github.com/nflverse/nflverse-data'
const CC_BY_URL = 'https://creativecommons.org/licenses/by/4.0/'

function ExternalLink({ label, url }: { label: string; url: string }) {
  return (
    <Pressable
      onPress={() => Linking.openURL(url)}
      accessibilityRole="link"
      hitSlop={HIT_SLOP}
    >
      {({ pressed }) => (
        <Text style={[styles.link, pressed && styles.linkPressed]}>{label}</Text>
      )}
    </Pressable>
  )
}

// No confidence line here: the parlay screen renders it as a ConfidenceBar at
// the top, and stating the same headline number twice on one screen reads as
// two different figures until you check.
export function ParlayDisplayFooter({ parlay }: { parlay: GeneratedParlay }) {
  return (
    <View style={styles.footer}>
      <LegalDisclaimer />

      {/* nflverse data is CC BY 4.0 — attribution is a licence condition
          wherever the data is surfaced, not a nicety. Mirrors the web
          client's ParlayDisplayFooter. */}
      <View style={styles.attribution}>
        <Text style={styles.meta}>EPA data via </Text>
        <ExternalLink label="nflverse" url={NFLVERSE_URL} />
        <Text style={styles.meta}>, </Text>
        <ExternalLink label="CC BY 4.0" url={CC_BY_URL} />
      </View>

      <Text style={styles.meta}>Generated by AI</Text>
    </View>
  )
}

const styles = StyleSheet.create({
  footer: { gap: spacing.xs },
  meta: { ...typography.bodySmall, color: colors.textSecondary },
  attribution: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap' },
  link: {
    ...typography.bodySmall,
    color: colors.textSecondary,
    textDecorationLine: 'underline',
  },
  linkPressed: { color: colors.text },
})
