// src/components/legal/legalDialogConfigs.tsx
import {
  AccountBalance as AccountBalanceIcon,
  Block as BlockIcon,
  CheckCircle as CheckCircleIcon,
  Gavel as GavelIcon,
  Info as InfoIcon,
  Security as SecurityIcon,
  Settings as SettingsIcon,
  Share as ShareIcon,
  Shield as ShieldIcon,
  Storage as StorageIcon,
  Warning as WarningIcon,
} from '@mui/icons-material'
import { BaseLegalDialogProps } from './BaseLegalDialog'
import type { LegalContent as LegalPageContent } from './LegalPage'

// Terms of Service Configuration
export const termsOfServiceConfig: Omit<
  BaseLegalDialogProps,
  'open' | 'onClose'
> = {
  title: 'Terms of Service',
  subtitle: 'Last updated September 8, 2026',
  icon: <GavelIcon />,
  themeColor: '#2e7d32',
  gradientColor: 'rgba(46, 125, 50, 0.1)',
  borderColor: 'rgba(46, 125, 50, 0.2)',
  buttonText: 'I Understand',
  headerNotice: {
    title: 'Important Notice',
    description:
      'By using ParlAId, you agree to these terms and conditions. This platform is designed for entertainment purposes only and does not facilitate real gambling or betting.',
    severity: 'warning',
  },
  sections: [
    {
      title: '1. Entertainment Only',
      description:
        'This application is for entertainment purposes only. No actual betting, wagering, or gambling takes place on this platform.',
      icon: <WarningIcon color="warning" />,
    },
    {
      title: '2. Age Requirement',
      description:
        'You must be 18 years or older to use this service. By accessing this platform, you confirm you meet this requirement.',
      icon: <CheckCircleIcon color="success" />,
    },
    {
      title: '3. AI-Generated Content',
      description:
        'All parlay suggestions are generated by artificial intelligence for entertainment purposes and do not guarantee outcomes.',
      icon: <CheckCircleIcon color="success" />,
    },
    {
      title: '4. No Liability',
      description:
        'We are not responsible for any decisions you make based on AI-generated suggestions. Use at your own discretion.',
      icon: <WarningIcon color="warning" />,
    },
    {
      title: '5. Responsible Use',
      description:
        'By using this service, you agree to use it responsibly and seek help if gambling becomes a problem.',
      icon: <CheckCircleIcon color="success" />,
    },
    {
      title: '6. Service Changes',
      description:
        'We reserve the right to modify or discontinue the service at any time without prior notice.',
      icon: <CheckCircleIcon color="success" />,
    },
  ],
  footerSection: {
    title: 'Contact Information',
    description:
      'If you have questions about these terms, please contact us at',
    contactInfo: 'admin@debugdad.com',
    bgColor: 'rgba(46, 125, 50, 0.05)',
    borderColor: 'rgba(46, 125, 50, 0.2)',
    titleColor: '#2e7d32',
  },
}

// Privacy Policy Configuration
export const privacyPolicyConfig: Omit<
  BaseLegalDialogProps,
  'open' | 'onClose'
> = {
  title: 'Privacy Policy',
  subtitle: 'Last updated September 8, 2026',
  icon: <SecurityIcon />,
  themeColor: '#1976d2',
  gradientColor: 'rgba(25, 118, 210, 0.1)',
  borderColor: 'rgba(25, 118, 210, 0.2)',
  buttonText: 'Got It',
  headerNotice: {
    title: 'Your Privacy Matters',
    description:
      'We are committed to protecting your privacy and being transparent about how we collect, use, and protect your information. This policy explains our data practices in simple terms.',
    chips: [{ label: 'GDPR Compliant', color: 'primary' }],
  },
  sections: [
    {
      title: 'Information We Collect',
      description:
        'We collect minimal information necessary to provide our service: authentication data (email, name), parlay history, and basic usage analytics to improve user experience.',
      icon: <StorageIcon color="primary" />,
    },
    {
      title: 'How We Use Your Information',
      description:
        'Your information is used solely to provide the AI parlay generation service, save your parlay history, and improve our platform. We do not use your data for advertising.',
      icon: <SettingsIcon color="primary" />,
    },
    {
      title: 'Data Security',
      description:
        'We implement industry-standard security measures including encryption, secure authentication, and regular security audits to protect your personal information.',
      icon: <ShieldIcon color="success" />,
    },
    {
      title: 'Third-Party Sharing',
      description:
        'We do not sell, rent, or share your personal information with third parties for marketing purposes. We only share data when required by law or to provide our service.',
      icon: <ShareIcon color="warning" />,
    },
    {
      title: 'Data Retention',
      description:
        'We retain your account information and parlay history as long as your account is active. You can request deletion of your data at any time.',
      icon: <StorageIcon color="primary" />,
    },
  ],
  footerSection: {
    title: 'Your Rights',
    description:
      'You can delete your account and everything in it at any time — from the Account tab on iPhone, or the menu under your name on the web. Deletion is immediate and permanent. Parlays you chose to share by link stay reachable by that link and carry no name or account. For privacy-related questions or requests, contact us at',
    contactInfo: 'admin@debugdad.com',
    bgColor: 'rgba(46, 125, 50, 0.05)',
    borderColor: 'rgba(46, 125, 50, 0.2)',
    titleColor: '#2e7d32',
  },
}

// Legal Disclaimer Configuration
export const legalDisclaimerConfig: Omit<
  BaseLegalDialogProps,
  'open' | 'onClose'
> = {
  title: 'Legal Disclaimer',
  subtitle: 'Important legal information and limitations',
  icon: <GavelIcon />,
  themeColor: '#ff9800',
  gradientColor: 'rgba(255, 152, 0, 0.1)',
  borderColor: 'rgba(255, 152, 0, 0.2)',
  buttonText: 'I Acknowledge',
  alertSection: {
    title: 'Important Legal Notice',
    description:
      'Please read these disclaimers carefully. By using ParlAId, you acknowledge and agree to these terms and limitations.',
    severity: 'warning',
  },
  sections: [
    {
      title: 'Entertainment Purpose Only',
      description:
        'This application is designed solely for entertainment and educational purposes. No actual betting, gambling, or wagering occurs on this platform.',
      icon: <InfoIcon color="info" />,
    },
    {
      title: 'No Outcome Guarantees',
      description:
        'AI-generated parlay suggestions are based on statistical analysis and historical data. They do not guarantee any outcomes. Sports betting involves significant risk.',
      icon: <WarningIcon color="warning" />,
    },
    {
      title: 'Not Financial or Betting Advice',
      description:
        'Nothing on this platform constitutes professional financial, betting, or investment advice. Users should make their own informed decisions and consult professionals.',
      icon: <BlockIcon color="error" />,
    },
    {
      title: 'Age and Legal Restrictions',
      description:
        'This service is restricted to users who are 18 years of age or older and legally permitted to view sports betting content in their jurisdiction.',
      icon: <AccountBalanceIcon color="primary" />,
    },
    {
      title: 'Limitation of Liability',
      description:
        'We are not liable for any losses, damages, or consequences resulting from the use of this entertainment platform or any decisions based on our content.',
      icon: <GavelIcon color="secondary" />,
    },
  ],
  footerSection: {
    title: 'Responsible Gambling Notice',
    description:
      'If you choose to place real bets elsewhere, please do so responsibly and within your means. Gambling can be addictive and lead to serious financial and personal problems. Need help? Call the National Problem Gambling Helpline at 1-800-522-4700 or visit gamblersanonymous.org',
    bgColor: 'rgba(244, 67, 54, 0.05)',
    borderColor: 'rgba(244, 67, 54, 0.2)',
    titleColor: '#f44336',
  },
}

// Support Page Configuration
//
// App Store Connect requires a Support URL to submit at all, and it has to be a
// page rather than a mailto. This is not a dialog — nothing in the app opens it
// — but it lives here so every piece of user-facing legal and support copy
// stays in one file.
export const supportConfig: LegalPageContent = {
  title: 'Support',
  subtitle: 'ParlAId — AI-generated NFL parlays, for entertainment',
  headerNotice: {
    title: 'Entertainment only',
    description:
      'ParlAId generates suggested parlays and explains the reasoning behind them. No wagers are placed through the app and no money changes hands. You must be 18 or older to use it.',
    severity: 'info',
  },
  sections: [
    {
      title: 'Getting help',
      description:
        'Email admin@debugdad.com with any question, bug report, or account request. Include the email address you signed in with so we can find your account. We answer everything, usually within a couple of days.',
      icon: <InfoIcon color="info" />,
    },
    {
      title: 'Deleting your account',
      description:
        'Delete your account from the Account tab on iPhone, or from the menu under your name on the web. Deletion removes your profile, your saved parlays and your generation history permanently and cannot be undone. Cancel a Pro subscription before deleting — neither the App Store nor Stripe cancels one because an account was removed.',
      icon: <BlockIcon color="error" />,
    },
    {
      title: 'Managing your subscription',
      description:
        'ParlAId Pro renews monthly and can be cancelled at any time. Subscriptions bought on iPhone are managed in Settings > your name > Subscriptions; subscriptions bought on the web are managed through the billing portal in the app. Deleting your account does not cancel a subscription — cancel it first.',
      icon: <AccountBalanceIcon color="primary" />,
    },
    {
      title: 'Gambling help',
      description:
        'If gambling is causing you or someone you know harm, call the National Council on Problem Gambling helpline at 1-800-522-4700, any time, free and confidential.',
      icon: <WarningIcon color="warning" />,
    },
  ],
  footerSection: {
    title: 'Contact',
    description: 'ParlAId is built and run by DebugDad LLC. Reach us at',
    contactInfo: 'admin@debugdad.com',
  },
}
