// Legal copy mirrored from the web client's legalDialogConfigs.tsx and
// ResponsibleGambling.tsx. Kept as plain data here (web embeds MUI icon
// elements in its config, which don't cross to React Native) so the wording
// stays identical across clients. If the web copy changes, change it here too.

export const CONTACT_EMAIL = 'admin@debugdad.com'
export const HELPLINE = '1-800-522-4700'
export const MINIMUM_AGE = 18

export interface LegalSection {
  title: string
  description: string
}

export interface LegalDocument {
  title: string
  subtitle: string
  notice?: { title: string; description: string }
  sections: LegalSection[]
  footer: { title: string; description: string; contact?: string }
}

export const termsOfService: LegalDocument = {
  title: 'Terms of Service',
  subtitle: 'Last updated September 8, 2026',
  notice: {
    title: 'Important Notice',
    description:
      'By using ParlAId, you agree to these terms and conditions. This platform is designed for entertainment purposes only and does not facilitate real gambling or betting.',
  },
  sections: [
    {
      title: '1. Entertainment Only',
      description:
        'This application is for entertainment purposes only. No actual betting, wagering, or gambling takes place on this platform.',
    },
    {
      title: '2. Age Requirement',
      description:
        'You must be 18 years or older to use this service. By accessing this platform, you confirm you meet this requirement.',
    },
    {
      title: '3. AI-Generated Content',
      description:
        'All parlay suggestions are generated by artificial intelligence for entertainment purposes and do not guarantee outcomes.',
    },
    {
      title: '4. No Liability',
      description:
        'We are not responsible for any decisions you make based on AI-generated suggestions. Use at your own discretion.',
    },
    {
      title: '5. Responsible Use',
      description:
        'By using this service, you agree to use it responsibly and seek help if gambling becomes a problem.',
    },
    {
      title: '6. Service Changes',
      description:
        'We reserve the right to modify or discontinue the service at any time without prior notice.',
    },
  ],
  footer: {
    title: 'Contact Information',
    description: 'If you have questions about these terms, please contact us at',
    contact: CONTACT_EMAIL,
  },
}

export const privacyPolicy: LegalDocument = {
  title: 'Privacy Policy',
  subtitle: 'Last updated September 8, 2026',
  notice: {
    title: 'Your Privacy Matters',
    description:
      'We are committed to protecting your privacy and being transparent about how we collect, use, and protect your information. This policy explains our data practices in simple terms.',
  },
  sections: [
    {
      title: 'Information We Collect',
      description:
        'We collect minimal information necessary to provide our service: authentication data (email, name), parlay history, and basic usage analytics to improve user experience.',
    },
    {
      title: 'How We Use Your Information',
      description:
        'Your information is used solely to provide the AI parlay generation service, save your parlay history, and improve our platform. We do not use your data for advertising.',
    },
    {
      title: 'Data Security',
      description:
        'We implement industry-standard security measures including encryption, secure authentication, and regular security audits to protect your personal information.',
    },
    {
      title: 'Third-Party Sharing',
      description:
        'We do not sell, rent, or share your personal information with third parties for marketing purposes. We only share data when required by law or to provide our service.',
    },
    {
      title: 'Data Retention',
      description:
        'We retain your account information and parlay history as long as your account is active. You can request deletion of your data at any time.',
    },
  ],
  footer: {
    title: 'Your Rights',
    description:
      'You have the right to access, update, or delete your personal information at any time. You can also export your data or request account deletion. For privacy-related questions or requests, contact us at',
    contact: CONTACT_EMAIL,
  },
}

export const legalDisclaimer: LegalDocument = {
  title: 'Legal Disclaimer',
  subtitle: 'Important legal information and limitations',
  notice: {
    title: 'Important Legal Notice',
    description:
      'Please read these disclaimers carefully. By using ParlAId, you acknowledge and agree to these terms and limitations.',
  },
  sections: [
    {
      title: 'Entertainment Purpose Only',
      description:
        'This application is designed solely for entertainment and educational purposes. No actual betting, gambling, or wagering occurs on this platform.',
    },
    {
      title: 'No Outcome Guarantees',
      description:
        'AI-generated parlay suggestions are based on statistical analysis and historical data. They do not guarantee any outcomes. Sports betting involves significant risk.',
    },
    {
      title: 'Not Financial or Betting Advice',
      description:
        'Nothing on this platform constitutes professional financial, betting, or investment advice. Users should make their own informed decisions and consult professionals.',
    },
    {
      title: 'Age and Legal Restrictions',
      description:
        'This service is restricted to users who are 18 years of age or older and legally permitted to view sports betting content in their jurisdiction.',
    },
    {
      title: 'Limitation of Liability',
      description:
        'We are not liable for any losses, damages, or consequences resulting from the use of this entertainment platform or any decisions based on our content.',
    },
  ],
  footer: {
    title: 'Responsible Gambling Notice',
    description:
      'If you choose to place real bets elsewhere, please do so responsibly and within your means. Gambling can be addictive and lead to serious financial and personal problems. Need help? Call the National Problem Gambling Helpline at 1-800-522-4700 or visit gamblersanonymous.org',
  },
}

export interface Helpline {
  name: string
  phone: string
  website: string
  description: string
  /** tel: target where the phone value is actually dialable. */
  dial?: string
}

export const HELPLINES: Helpline[] = [
  {
    name: 'National Problem Gambling Helpline',
    phone: '1-800-522-4700',
    dial: '18005224700',
    website: 'ncpgambling.org',
    description: '24/7 confidential support for problem gambling',
  },
  {
    name: 'Gamblers Anonymous',
    phone: 'Local chapter meetings',
    website: 'gamblersanonymous.org',
    description: 'Peer support groups and recovery programs',
  },
  {
    name: 'National Suicide Prevention Lifeline',
    phone: '988',
    dial: '988',
    website: 'suicidepreventionlifeline.org',
    description: 'Crisis support and mental health resources',
  },
  {
    name: 'Crisis Text Line',
    phone: 'Text HOME to 741741',
    website: 'crisistextline.org',
    description: 'Free, 24/7 crisis support via text message',
  },
]

export const WARNING_SIGNS = [
  'Spending more money on betting than you can afford to lose',
  'Chasing losses with bigger or more frequent bets',
  'Lying to family and friends about gambling activities',
  'Neglecting work, school, or family responsibilities to gamble',
  'Feeling anxious, depressed, or irritable when not gambling',
  'Borrowing money or selling possessions to fund gambling',
  'Unable to cut back or stop gambling despite wanting to',
  'Gambling to escape problems or negative emotions',
]

export const RESPONSIBLE_PRACTICES = [
  'Set strict limits on time and money spent gambling',
  'Never gamble money you cannot afford to lose',
  'View gambling as entertainment, not a way to make money',
  'Take regular breaks and avoid gambling when emotional',
  'Keep track of time and money spent gambling',
  'Do not chase losses with bigger bets',
  'Seek help if gambling becomes a problem',
  'Use self-exclusion tools when available',
]
