import Ionicons from '@expo/vector-icons/Ionicons'
import { Image } from 'expo-image'
import { useState } from 'react'
import { ScrollView, StyleSheet, Text, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'

import { AuthSheet } from '@/components/auth/AuthSheet'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'
import { colors, spacing, typography } from '@/lib/theme/designTokens'

// Mirrors the web AuthGate's four cards, same copy.
const FEATURES = [
  {
    icon: 'bulb-outline',
    title: 'AI-Powered Analysis',
    description:
      'Advanced algorithms analyze team stats, player performance, and matchup data to generate intelligent parlay recommendations.',
  },
  {
    icon: 'american-football-outline',
    title: 'Real-Time NFL Data',
    description:
      'Live roster data and current season stats ensure accurate player props and up-to-date betting information.',
  },
  {
    icon: 'time-outline',
    title: 'Parlay History',
    description:
      'Save and track your generated parlays. Build your betting portfolio and analyze AI recommendations over time.',
  },
  {
    icon: 'shield-checkmark-outline',
    title: 'Secure & Private',
    description:
      'Your data is protected with enterprise-grade security. Only you can access your saved parlays and betting history.',
  },
] as const

const SAMPLE_LEGS = [
  {
    pick: 'Chiefs -3.5 vs Ravens',
    reason: 'Home field advantage with strong rushing defense',
  },
  {
    pick: 'Travis Kelce Over 65.5 Rec Yards',
    reason: 'High target share against weak TE coverage',
  },
  {
    pick: 'Over 48.5 Total Points',
    reason: 'Both teams averaging 28+ PPG this season',
  },
] as const

export function AuthGate() {
  const [sheetOpen, setSheetOpen] = useState(false)
  const [startOnSignUp, setStartOnSignUp] = useState(false)

  const open = (signUp: boolean) => {
    setStartOnSignUp(signUp)
    setSheetOpen(true)
  }

  return (
    <SafeAreaView style={styles.screen} edges={['top']}>
      <ScrollView contentContainerStyle={styles.scroll}>
        <View style={styles.hero}>
          <Image
            source={require('@/assets/images/parlaid-wordmark-white.png')}
            style={styles.wordmark}
            contentFit="contain"
            accessibilityLabel="ParlAId — AI powered NFL parlay generator"
          />
          <Text style={styles.tagline}>
            Harness the power of AI to generate intelligent 3-leg parlays for
            NFL games. Get data-driven insights and build your winning strategy.
          </Text>

          <Button
            label="Get started free"
            icon="log-in-outline"
            onPress={() => open(true)}
            style={styles.heroBtn}
          />
          <Button
            variant="outline"
            label="Sign in"
            onPress={() => open(false)}
            style={styles.heroBtn}
          />
        </View>

        <Card style={styles.sampleCard}>
          <View style={styles.sampleHeader}>
            <Ionicons name="dice-outline" size={20} color={colors.primaryBright} />
            <Text style={styles.sampleTitle}>Sample AI parlay</Text>
            <Text style={styles.sampleOdds}>+575</Text>
          </View>
          {SAMPLE_LEGS.map(leg => (
            <Card tone="inset" key={leg.pick} style={styles.sampleLeg}>
              <Text style={styles.sampleLegPick}>{leg.pick}</Text>
              <Text style={styles.sampleLegReason}>{leg.reason}</Text>
            </Card>
          ))}
          <Text style={styles.sampleFooter}>
            Generated by AI · Sign in to create your own
          </Text>
        </Card>

        <View style={styles.features}>
          {FEATURES.map(feature => (
            <Card key={feature.title} style={styles.featureCard}>
              <Ionicons name={feature.icon} size={28} color={colors.primaryBright} />
              <Text style={styles.featureTitle}>{feature.title}</Text>
              <Text style={styles.featureBody}>{feature.description}</Text>
            </Card>
          ))}
        </View>

        <View style={styles.cta}>
          <Text style={styles.ctaTitle} accessibilityRole="header">
            Ready to build winning parlays?
          </Text>
          <Text style={styles.ctaBody}>
            Join thousands of bettors using AI to make smarter NFL parlay
            decisions. Create your free account and start generating parlays in
            seconds.
          </Text>
          <Button
            label="Create free account"
            icon="log-in-outline"
            onPress={() => open(true)}
            style={styles.heroBtn}
          />
        </View>

        <View style={styles.footer}>
          <Text style={styles.footerText}>
            © {new Date().getFullYear()} ParlAId. AI-generated parlays for
            entertainment only.
          </Text>
        </View>
      </ScrollView>

      <AuthSheet
        visible={sheetOpen}
        startOnSignUp={startOnSignUp}
        onClose={() => setSheetOpen(false)}
      />
    </SafeAreaView>
  )
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  scroll: { padding: spacing.md, paddingBottom: spacing.xxl, gap: spacing.xl },

  hero: { alignItems: 'center', gap: spacing.md, paddingTop: spacing.xl },
  wordmark: { width: '80%', height: 88 },
  tagline: {
    ...typography.body,
    color: colors.textSecondary,
    textAlign: 'center',
  },

  heroBtn: { alignSelf: 'stretch' },

  sampleCard: { gap: spacing.sm },
  sampleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  sampleTitle: { ...typography.title, color: colors.text, flex: 1 },
  sampleOdds: { ...typography.numeric, color: colors.primaryBright },
  sampleLeg: { gap: spacing.xs },
  sampleLegPick: { ...typography.label, color: colors.text },
  sampleLegReason: { ...typography.bodySmall, color: colors.textSecondary },
  sampleFooter: {
    ...typography.bodySmall,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: spacing.xs,
  },

  features: { gap: spacing.md },
  featureCard: { gap: spacing.sm },
  featureTitle: { ...typography.title, color: colors.text },
  featureBody: { ...typography.bodySmall, color: colors.textSecondary },

  cta: { gap: spacing.md, alignItems: 'center' },
  ctaTitle: {
    ...typography.heading,
    color: colors.text,
    textAlign: 'center',
  },
  ctaBody: {
    ...typography.body,
    color: colors.textSecondary,
    textAlign: 'center',
  },

  footer: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.divider,
    paddingTop: spacing.md,
  },
  footerText: {
    ...typography.bodySmall,
    color: colors.textSecondary,
    textAlign: 'center',
  },
})
