// packages/shared/src/types.ts
// SINGLE SOURCE OF TRUTH - All types defined here

// ===== CORE STRATEGY TYPES =====
export interface StrategyConfig {
  name: string
  description?: string
  temperature?: number
  riskLevel?: 'conservative' | 'medium' | 'aggressive'
  riskProfile?: 'low' | 'medium' | 'high'
  confidenceRange?: [number, number]
}

export interface VarietyFactors {
  strategy?: string
  focusArea?: string
  playerTier?: string
  gameScript?: string
  marketBias?: string
  riskTolerance?: number
  focusPlayer?: string
}

// ===== PARLAY TYPES =====

/**
 * Game summary analysis generated by AI for display in the UI
 */
export interface GameSummary {
  /** Detailed analysis of team matchups and key factors */
  matchupAnalysis: string
  /** Expected game flow and tempo */
  gameFlow:
    | 'high_scoring_shootout'
    | 'defensive_grind'
    | 'balanced_tempo'
    | 'potential_blowout'
  /** Array of key factors that could influence the game */
  keyFactors: string[]
  /** AI prediction for the game outcome */
  prediction: string
  /** Confidence level (1-10) in the overall analysis */
  confidence: number
}

/**
 * Individual parlay leg for UI display
 */
export interface ParlayLeg {
  id: string
  betType: 'spread' | 'total' | 'moneyline' | 'player_prop'
  selection: string
  target: string
  reasoning: string
  confidence: number
  odds: string
}

export interface ParlayOptions {
  strategy?: string
  variety?: VarietyFactors
  riskTolerance?: number
  temperature?: number
  maxLegs?: number
  /** AI provider selection - used by DevStatus toggle */
  provider?: 'openai' | 'mock' | 'auto'
}

/**
 * Complete GeneratedParlay definition - includes ALL fields
 * No more extending/merging needed
 */
export interface GeneratedParlay {
  // Core fields (always present)
  gameId: string
  legs: Array<{
    type: 'spread' | 'total' | 'moneyline' | 'player_prop'
    selection: string
    threshold?: number
    price?: number
    rationale?: string
  }>
  notes?: string

  // Extended fields (optional)
  /** UI-specific ID for tracking */
  id?: string
  /** Game context string for display (e.g., "Chiefs @ Bills - Week 14") */
  gameContext?: string
  /** Overall AI reasoning for the parlay selection */
  aiReasoning?: string
  /** Overall confidence score (1-10) for the entire parlay */
  overallConfidence?: number
  /** Estimated odds for the parlay (e.g., "+250") */
  estimatedOdds?: string
  /** AI-generated game analysis and summary */
  gameSummary?: GameSummary
  /** ISO timestamp of when the parlay was created */
  createdAt?: string
  /** Timestamp for saved parlays (typed as 'any' to avoid Firebase dependency) */
  savedAt?: any
}

export interface GenerateParlayRequest {
  gameId: string
  options?: ParlayOptions
}

export interface GenerateParlayResponse {
  success: boolean
  data?: GeneratedParlay
  error?: { code?: string; message: string; details?: unknown }
  metadata?: {
    provider: string
    model: string
    tokens?: number
    latency: number
    confidence: number
    fallbackUsed: boolean
    attemptCount: number
    requestedProvider?: string
    actualProvider?: string
    providerMatch?: boolean
  }
}

export interface ParlayGenerationResult {
  parlay: GeneratedParlay
  rateLimitInfo?: {
    remaining: number
    total: number
    resetTime: string
    currentCount: number
  }
}

export interface SavedParlay extends GeneratedParlay {
  userId: string
  savedAt: any // Will be typed as Timestamp in frontend
}

// ===== NFL TYPES =====

export interface NFLTeam {
  id: string
  displayName: string
  abbreviation: string
  location: string
  name: string
  color: string
  alternateColor: string
  logo: string
}

export interface Position {
  id: string
  name: string
  abbreviation: string
  displayName: string
  leaf: boolean
}

export interface NFLPlayer {
  id: string
  displayName: string
  fullName: string
  jersey: string
  position: Position
  age?: number
  experience?: number
  college?: string
}

export interface NFLGame {
  id: string
  week: number
  awayTeam: NFLTeam
  homeTeam: NFLTeam
  startTime: string
  status: string
  date: string
  venue?: string
}

export interface GameRosters {
  gameId: string
  home: NFLPlayer[]
  away: NFLPlayer[]
  // Legacy aliases for UI compatibility
  homeRoster?: NFLPlayer[]
  awayRoster?: NFLPlayer[]
}

// ===== DATA ORCHESTRATION TYPES =====

export interface Weather {
  condition: 'indoor' | 'clear' | 'rain' | 'snow' | 'wind'
  temperature?: number
  windSpeed?: number
  humidity?: number
}

export interface InjuryReport {
  playerId: string
  playerName: string
  position: string
  team: string
  injuryType: string
  status: 'out' | 'doubtful' | 'questionable' | 'probable'
  bodyPart: string
  expectedReturn?: string
}

export interface Trend {
  id: string
  type: 'team' | 'player' | 'matchup'
  description: string
  value: number
  confidence: number
  timeframe: string
}

export interface MarketLine {
  id: string
  type: 'spread' | 'total' | 'moneyline' | 'player_prop'
  value: number
  odds: number
  sportsbook: string
  lastUpdated: string
}

export interface UnifiedGameData {
  game: NFLGame
  rosters: GameRosters
  weather?: Weather
  injuries?: InjuryReport
  trends: Trend[]
  lines: MarketLine[]
}

// ===== ERROR TYPES =====

export interface CloudFunctionError {
  code: string
  message: string
  details?: unknown
}
