import { Box, Link, Typography } from '@mui/material'
import React from 'react'
import type { GeneratedParlay } from '../../types'
import { LegalDisclaimer } from '../legal/LegalDisclaimer'

const ParlayDisplayFooter: React.FC<{ parlay: GeneratedParlay }> = ({ parlay }) => {
  return (
    <Box
      sx={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 2,
        flexWrap: 'wrap',
      }}
    >
      <Typography variant="caption" color="text.secondary" sx={{ fontVariantNumeric: 'tabular-nums' }}>
        Overall confidence {Math.round(parlay.parlayConfidence * 100)}%
      </Typography>
      <LegalDisclaimer variant="inline" />
      <Typography variant="caption" color="text.secondary">
        EPA data via{' '}
        <Link
          href="https://github.com/nflverse/nflverse-data"
          target="_blank"
          rel="noopener noreferrer"
          color="inherit"
          underline="hover"
        >
          nflverse
        </Link>
        ,{' '}
        <Link
          href="https://creativecommons.org/licenses/by/4.0/"
          target="_blank"
          rel="noopener noreferrer"
          color="inherit"
          underline="hover"
        >
          CC BY 4.0
        </Link>
      </Typography>
      <Typography variant="caption" color="text.secondary">
        Generated by AI
      </Typography>
    </Box>
  )
}

export default ParlayDisplayFooter
