import { Box, Typography } from '@mui/material'
import React from 'react'
import useParlayStore from '../../store/parlayStore'
import { LegalDisclaimer } from '../legal/LegalDisclaimer'

const ParlayDisplayFooter: React.FC = () => {
  const parlay = useParlayStore(state => state.parlay)

  if (!parlay) {
    return null
  }

  return (
    <Box
      sx={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        mt: 4,
      }}
    >
      <Typography variant="caption" color="text.secondary">
        Overall Confidence: {Math.round(parlay.parlayConfidence * 100)}%
      </Typography>
      <LegalDisclaimer variant="inline" showResponsibleGamblingLink={true} />
      <Typography
        variant="caption"
        color="text.secondary"
        sx={{ fontWeight: 500 }}
      >
        ✨ Generated by AI
      </Typography>
    </Box>
  )
}

export default ParlayDisplayFooter
