import { Alert, Box, Card, CardContent, Chip, Container, Typography } from '@mui/material'
import React, { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { API_CONFIG } from '../../config/api'
import type { GeneratedParlay } from '../../types'
import { formatOdds } from '../../utils'
import { LoadingScreen } from '../LoadingScreen'
import ParlAIdLogo from '../ParlAIdLogo'
import ParlayLegView from './ParlayLegView'

type SharedParlay = GeneratedParlay & { sharedAt?: string }

// The read-only view behind a share link. Served from the API's sanitized
// copy, so it renders whatever the owner chose to publish and never carries
// their account with it.
export const SharedParlayView: React.FC = () => {
  const { shareId } = useParams<{ shareId: string }>()
  const [parlay, setParlay] = useState<SharedParlay | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let active = true
    fetch(`${API_CONFIG.CLOUD_FUNCTIONS.baseURL}/shared/${shareId}`)
      .then(async res => {
        if (!res.ok) {
          throw new Error(
            res.status === 404
              ? 'This parlay is no longer shared.'
              : 'Could not load this parlay.'
          )
        }
        return res.json()
      })
      .then(data => active && setParlay(data))
      .catch(err => active && setError(err.message))
    return () => {
      active = false
    }
  }, [shareId])

  if (error) {
    return (
      <Container maxWidth="md" sx={{ py: 6 }}>
        <Alert severity="info">{error}</Alert>
      </Container>
    )
  }
  if (!parlay) {
    return <LoadingScreen />
  }

  const outcome =
    parlay.grading?.status === 'graded' ? parlay.grading.parlayOutcome : null

  return (
    <Container maxWidth="md" sx={{ py: 4 }}>
      <Box sx={{ mb: 3 }}>
        <ParlAIdLogo height={{ xs: 44, sm: 60 }} />
      </Box>

      <Card variant="outlined" sx={{ mb: 3 }}>
        <CardContent>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, flexWrap: 'wrap' }}>
            <Typography variant="h6" sx={{ fontWeight: 600, flex: 1 }}>
              {parlay.gameContext}
            </Typography>
            {outcome && (
              <Chip
                size="small"
                label={outcome[0].toUpperCase() + outcome.slice(1)}
                color={
                  outcome === 'won'
                    ? 'success'
                    : outcome === 'lost'
                      ? 'error'
                      : outcome === 'partial'
                        ? 'warning'
                        : 'default'
                }
              />
            )}
            <Typography
              variant="h6"
              sx={{ fontWeight: 600, fontVariantNumeric: 'tabular-nums' }}
            >
              {formatOdds(parlay.combinedOdds)}
            </Typography>
          </Box>
        </CardContent>
      </Card>

      {parlay.legs.map((leg, i) => (
        <ParlayLegView key={`${parlay.shareId}-${leg.betType}-${leg.selection}`} leg={leg} index={i} />
      ))}

      <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 3 }}>
        Shared from ParlAId · generated by AI · for entertainment only
      </Typography>
    </Container>
  )
}

export default SharedParlayView
